spring:
  datasource:
    driver-class-name=org: org.H2.Driver
    url:  jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
  h2:
    console:
      enabled: true
      path: /h2console
      web-allow-others: true